exports.compositoresListPage = function(slist, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-brown">
                    <h1>Lista de compositores
                    <a class="w3-btn w3-round w3-white" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>
                        ${slist[i].id}
                    </td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>]
                        [<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-brown">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.compositorFormPage = function(d, periodos) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-brown">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Informação</legend>
                        <label>ID</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Biografia</label>
                        <textarea class="w3-input w3-round" name="bio"></textarea>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                        <label>Período</label>
                        <select class="w3-select w3-round" name="periodo">
                            <option value="">Selecione uma opção</option>`;
                            for(let i = 0; i < periodos.length; i++) {
                                pagHTML += `<option value="${periodos[i].nome}">${periodos[i].nome}</option>`;
                            }

    pagHTML += `
                        </select>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-brown w3-mb-2" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-brown">
                    <h5>Gerado por EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</h5>
                </footer>
            
            </div>
    `;
    return pagHTML;
};


exports.compositorFormEditPage = function(compositor, periodos, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-brown">
                    <h2>Editar Compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Informação</legend>
                        <label>ID</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${compositor.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${compositor.nome}"/>
                        <label>Biografia</label>
                        <textarea class="w3-input w3-round" name="bio">${compositor.bio}</textarea>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value="${compositor.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value="${compositor.dataObito}"/>
                        <label>Período</label>
                        <select class="w3-select w3-round" name="periodo">`;
                            for(let i = 0; i < periodos.length; i++) {
                                pagHTML += `<option value="${periodos[i].nome}" ${compositor.periodo === periodos[i].nome ? 'selected' : ''}>${periodos[i].nome}</option>`;
                            }

    pagHTML += `
                        </select>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-brown w3-mb-2" type="submit">Atualizar</button>
                </form>

                <footer class="w3-container w3-brown">
                    <h5>Gerado por EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</h5>
                </footer>
            
            </div>
    `;
    return pagHTML;
}


exports.compositorPage = function(compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>${compositor.nome}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-brown">
                <h1>${compositor.nome}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>ID: </b> ${compositor.id}</li>
                    <li><b>Biografia: </b> ${compositor.bio}</li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${compositor.dataObito}</li>
                    <li><b>Período: </b> ${compositor.periodo}</li>
                </ul>
            </div>
            <footer class="w3-container w3-brown">
                <h5>Gerado por EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</h5>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}


exports.periodosListPage = function(periodos, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de Períodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-brown">
                    <h1>Lista de Períodos
                    <a class="w3-btn w3-round w3-white" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < periodos.length ; i++){
        pagHTML += `
                <tr>
                    <td>
                        ${periodos[i].id}
                    </td>
                    <td>
                        <a href="/periodos/${periodos[i].id}">
                            ${periodos[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${periodos[i].id}">Edit</a>]
                        [<a href="/periodos/delete/${periodos[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-brown">
                    <h5>Gerado por EngWeb2024 em ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.periodoFormPage = function(d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Período Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-brown">
                    <h2>Período Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Informação</legend>
                        <label>ID</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-brown w3-mb-2" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-brown">
                    <h5>Gerado por EngWeb2024 em ${d} - [<a href="/periodos">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
}


exports.periodoFormEditPage = function(periodo, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar Período</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-brown">
                    <h2>Editar Período</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Informação</legend>
                        <label>ID</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${periodo.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${periodo.nome}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-brown w3-mb-2" type="submit">Atualizar</button>
                </form>

                <footer class="w3-container w3-brown">
                    <h5>Gerado por EngWeb2024 em ${d} - [<a href="/periodos">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}


exports.periodoPage = function(periodo, d ){
    var pagHTML = `
    <html>
    <head>
        <title>${periodo.nome}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-brown">
                <h1>${periodo.nome}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>ID: </b> ${periodo.id}</li>
                </ul>
            </div>
            <footer class="w3-container w3-brown">
                <h5>Gerado por EngWeb2024 em ${d} - [<a href="/periodos">Voltar</a>]</h5>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}


exports.errorPage = function(errorMessage, d){
    return `

    <html>
    <head>
        <title>Error</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-brown">
            <p>Error Page</p>
            </header>

            <div class="w3-container">
            <p>${d}: Error: ${errorMessage}</p>
            </div>
            </div>
            <footer class="w3-container w3-brown">
                <h5>Gerado por EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</h5>
            </footer>
        </div>
    </body>
    </html>

    `
}
